name: Prettier + Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write **/*.js

  get-my-commits-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: React Build
        run: |
          cd get-my-commits-dev
          npm run build
          mkdir -p ../get-my-commits
          rm -rf ../get-my-commits
          mkdir -p ../get-my-commits
          mv -r build/ ../get-my-commits/
      
      - name: Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
      - name: Push Changes
        run: |
          git commit -am "built commit getter"
          git push